import { STATUS } from '../constants.js';
import { withSamplePhotos } from './samplePhotos.js';

/**
 * Shared survey results from other RoomCompare users.
 *
 * Read-only reference data, held as a static module rather than written to
 * storage: it cannot be corrupted and it does not consume the user's quota.
 * Accounts keep each user's own surveys and share nothing, so authorship
 * is simulated.
 *
 * Photos come from the sample set that ships with the app. The rotation
 * starts two sets on from the user's own samples, so the two lists differ.
 *
 * The prototype's Community tab listed the user's OWN published surveys,
 * which is not what the requirement describes. These are separate records.
 */

const CAMPUS = { lat: -7.9526, lng: 112.6148, label: 'Universitas Brawijaya' };

export const communitySurveys = withSamplePhotos([
  {
    id: 'com-kartika',
    ownerId: 'user-rahma',
    ownerName: 'Rahma',
    status: STATUS.PUBLISHED,
    createdAt: '2026-07-19T11:00:00.000Z',
    updatedAt: '2026-07-19T11:00:00.000Z',
    kos: {
      name: 'Kos Kartika',
      type: 'female',
      contactPhone: '0810-6677-2233',
      kosLocation: { lat: -7.9448, lng: 112.6135, label: 'Ketawanggede, Malang', address: 'Jalan Kartika 5, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 0.9,
      rent: 1650000,
    },
    room: {
      lengthM: 3.6,
      widthM: 3.2,
      facilities: ['Mattress', 'Wardrobe', 'AC', 'Table', 'Chair', 'Window', 'Includes electricity'],
      cleanliness: 4,
      internet: 4,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Western-style toilet', 'Water heater'], photoIds: [] },
    shared: {
      facilities: ['Wifi', 'Motorcycle parking', 'Kitchen', 'Washing machine', 'Refrigerator'],
      photoIds: [],
    },
    surroundings: ['Minimarket / supermarket', 'Eatery (warung makan)', 'ATM / bank', 'Pharmacy / clinic'],
    additional: {
      security: 4,
      notes: 'Walking distance to campus. Curfew at 11pm and the owner lives on site.',
      videoIds: [],
    },
  },
  {
    id: 'com-pondok-biru',
    ownerId: 'user-dimas',
    ownerName: 'Dimas',
    status: STATUS.PUBLISHED,
    createdAt: '2026-07-28T15:30:00.000Z',
    updatedAt: '2026-07-28T15:30:00.000Z',
    kos: {
      name: 'Pondok Biru',
      type: 'male',
      contactPhone: '0810-4411-3322',
      kosLocation: { lat: -7.9302, lng: 112.6221, label: 'Blimbing, Malang', address: 'Jalan Pondok Biru 11, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 3.4,
      rent: 950000,
    },
    room: {
      lengthM: 3,
      widthM: 2.5,
      facilities: ['Mattress', 'Wardrobe', 'Fan', 'Table', 'Window'],
      cleanliness: 2,
      internet: 2,
      photoIds: [],
    },
    bathroom: { facilities: ['Outdoor bathroom', 'Squat toilet'], photoIds: [] },
    shared: { facilities: ['Motorcycle parking', 'Kitchen'], photoIds: [] },
    surroundings: ['Eatery (warung makan)', 'Minimarket / supermarket'],
    additional: {
      security: 2,
      notes: 'Cheapest one I found. Basic, and the ride to campus takes about fifteen minutes.',
      videoIds: [],
    },
  },
  {
    id: 'com-griya-asri',
    ownerId: 'user-sari',
    ownerName: 'Sari',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-03T09:45:00.000Z',
    updatedAt: '2026-08-03T09:45:00.000Z',
    kos: {
      name: 'Griya Asri',
      type: 'mixed',
      contactPhone: '0810-9988-7766',
      kosLocation: { lat: -7.9487, lng: 112.6077, label: 'Dinoyo, Malang', address: 'Jalan Griya Asri 8, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 1.4,
      rent: 1450000,
    },
    room: {
      lengthM: 3.4,
      widthM: 3,
      facilities: ['Mattress', 'Wardrobe', 'AC', 'Fan', 'Table', 'Chair', 'Dispenser', 'Window'],
      cleanliness: 3,
      internet: 3,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Western-style toilet'], photoIds: [] },
    shared: {
      facilities: ['Wifi', 'Motorcycle parking', 'Car parking', 'Kitchen', 'Laundry', 'Dispenser'],
      photoIds: [],
    },
    surroundings: [
      'Minimarket / supermarket',
      'Eatery (warung makan)',
      'Laundry',
      'Place of worship',
      'Gym / sports facilities',
    ],
    additional: {
      security: 3,
      notes: 'Electricity is billed separately, so budget a little above the listed rent.',
      videoIds: [],
    },
  },
  {
    id: 'com-wisma-cempaka',
    ownerId: 'user-bagus',
    ownerName: 'Bagus',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-09T18:10:00.000Z',
    updatedAt: '2026-08-09T18:10:00.000Z',
    kos: {
      name: 'Wisma Cempaka',
      type: 'female',
      contactPhone: '0810-5544-6677',
      kosLocation: { lat: -7.9601, lng: 112.6203, label: 'Sukun, Malang', address: 'Jalan Wisma Cempaka 6, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 4.1,
      rent: 1100000,
    },
    room: {
      lengthM: 3.2,
      widthM: 3,
      facilities: ['Mattress', 'Wardrobe', 'Fan', 'Table', 'Chair', 'Window', 'Includes electricity'],
      cleanliness: 4,
      internet: 3,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Squat toilet'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Kitchen', 'Washing machine'], photoIds: [] },
    surroundings: ['Minimarket / supermarket', 'Eatery (warung makan)', 'Place of worship', 'ATM / bank'],
    additional: {
      security: 3,
      notes: 'Very clean and quiet, but far enough out that you would want a motorbike.',
      videoIds: [],
    },
  },
  {
    id: 'com-mawar',
    ownerId: 'user-intan',
    ownerName: 'Intan',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-12T08:20:00.000Z',
    updatedAt: '2026-08-12T08:20:00.000Z',
    kos: {
      name: 'Kos Mawar Putih',
      type: 'female',
      contactPhone: '0810-1234-5678',
      kosLocation: { lat: -7.9412, lng: 112.6198, label: 'Lowokwaru, Malang', address: 'Jalan Bunga Mawar, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 1.7,
      rent: 1750000,
    },
    room: {
      lengthM: 4,
      widthM: 3.5,
      facilities: ['Mattress', 'Wardrobe', 'AC', 'Table', 'Chair', 'Refrigerator', 'Window', 'Includes electricity'],
      cleanliness: 4,
      internet: 4,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Western-style toilet', 'Water heater'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Car parking', 'Kitchen', 'Washing machine', 'Dispenser'], photoIds: [] },
    surroundings: ['Minimarket / supermarket', 'Eatery (warung makan)', 'Pharmacy / clinic', 'ATM / bank', 'Gym / sports facilities'],
    additional: { security: 4, notes: 'The most complete one I saw, and priced accordingly.', videoIds: [] },
  },
  {
    id: 'com-tirta',
    ownerId: 'user-yoga',
    ownerName: 'Yoga',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-15T14:05:00.000Z',
    updatedAt: '2026-08-15T14:05:00.000Z',
    kos: {
      name: 'Kos Tirta',
      type: 'male',
      contactPhone: '0810-3322-1100',
      kosLocation: { lat: -7.9366, lng: 112.6024, label: 'Tlogomas, Malang', address: 'Jalan Tirto Utomo, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 2.6,
      rent: 1050000,
    },
    room: {
      lengthM: 3,
      widthM: 2.8,
      facilities: ['Mattress', 'Wardrobe', 'Fan', 'Table', 'Window'],
      cleanliness: 3,
      internet: 3,
      photoIds: [],
    },
    bathroom: { facilities: ['Outdoor bathroom', 'Squat toilet'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Kitchen', 'Laundry'], photoIds: [] },
    surroundings: ['Eatery (warung makan)', 'Minimarket / supermarket', 'Place of worship'],
    additional: { security: 3, notes: 'Plain but tidy, and the owner is easy to reach.', videoIds: [] },
  },
  {
    id: 'com-anggrek',
    ownerId: 'user-putri',
    ownerName: 'Putri',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-18T09:30:00.000Z',
    updatedAt: '2026-08-18T09:30:00.000Z',
    kos: {
      name: 'Kos Anggrek',
      type: 'female',
      contactPhone: '0810-9090-4545',
      kosLocation: { lat: -7.9538, lng: 112.6091, label: 'Dinoyo, Malang', address: 'Jalan Anggrek, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 1.2,
      rent: 1550000,
    },
    room: {
      lengthM: 3.4,
      widthM: 3.2,
      facilities: ['Mattress', 'Wardrobe', 'AC', 'Fan', 'Table', 'Chair', 'Dispenser', 'Window', 'Includes electricity'],
      cleanliness: 4,
      internet: 4,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Western-style toilet'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Kitchen', 'Washing machine', 'Laundry'], photoIds: [] },
    surroundings: ['Minimarket / supermarket', 'Eatery (warung makan)', 'Laundry', 'Place of worship'],
    additional: { security: 4, notes: 'Close to campus with a proper gate and a night guard.', videoIds: [] },
  },
  {
    id: 'com-bagas',
    ownerId: 'user-fajar',
    ownerName: 'Fajar',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-21T17:45:00.000Z',
    updatedAt: '2026-08-21T17:45:00.000Z',
    kos: {
      name: 'Kos Bagas',
      type: 'mixed',
      contactPhone: '0810-7788-9900',
      kosLocation: { lat: -7.9285, lng: 112.6157, label: 'Blimbing, Malang', address: 'Jalan Bagas Raya, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 3.1,
      rent: 890000,
    },
    room: {
      lengthM: 2.8,
      widthM: 2.5,
      facilities: ['Mattress', 'Wardrobe', 'Fan'],
      cleanliness: 2,
      internet: 2,
      photoIds: [],
    },
    bathroom: { facilities: ['Outdoor bathroom', 'Squat toilet'], photoIds: [] },
    shared: { facilities: ['Motorcycle parking'], photoIds: [] },
    surroundings: ['Eatery (warung makan)'],
    additional: { security: 2, notes: 'Cheapest I have seen near here. You get what you pay for.', videoIds: [] },
  },
  {
    id: 'com-harmoni',
    ownerId: 'user-nadia',
    ownerName: 'Nadia',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-25T11:15:00.000Z',
    updatedAt: '2026-08-25T11:15:00.000Z',
    kos: {
      name: 'Kos Harmoni',
      type: 'female',
      contactPhone: '0810-2468-1357',
      kosLocation: { lat: -7.9471, lng: 112.6242, label: 'Sumbersari, Malang', address: 'Jalan Harmoni, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 2.0,
      rent: 1300000,
    },
    room: {
      lengthM: 3.2,
      widthM: 3,
      facilities: ['Mattress', 'Wardrobe', 'Fan', 'Table', 'Chair', 'Window', 'Includes electricity'],
      cleanliness: 3,
      internet: 3,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Squat toilet', 'Water heater'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Kitchen', 'Refrigerator', 'Dispenser'], photoIds: [] },
    surroundings: ['Minimarket / supermarket', 'Eatery (warung makan)', 'ATM / bank', 'Place of worship'],
    additional: { security: 3, notes: 'Shared fridge and dispenser, which suited me.', videoIds: [] },
  },
  {
    id: 'com-cendana',
    ownerId: 'user-aldi',
    ownerName: 'Aldi',
    status: STATUS.PUBLISHED,
    createdAt: '2026-08-29T13:00:00.000Z',
    updatedAt: '2026-08-29T13:00:00.000Z',
    kos: {
      name: 'Kos Cendana',
      type: 'male',
      contactPhone: '0810-1122-3344',
      kosLocation: { lat: -7.9603, lng: 112.6118, label: 'Sukun, Malang', address: 'Jalan Cendana, Malang' },
      campusLocation: CAMPUS,
      distanceKm: 3.8,
      rent: 1150000,
    },
    room: {
      lengthM: 3.6,
      widthM: 3,
      facilities: ['Mattress', 'Wardrobe', 'AC', 'Table', 'Chair', 'Window'],
      cleanliness: 3,
      internet: 2,
      photoIds: [],
    },
    bathroom: { facilities: ['Indoor bathroom', 'Western-style toilet'], photoIds: [] },
    shared: { facilities: ['Wifi', 'Motorcycle parking', 'Car parking', 'Kitchen'], photoIds: [] },
    surroundings: ['Eatery (warung makan)', 'Minimarket / supermarket', 'Gym / sports facilities'],
    additional: { security: 3, notes: 'Has AC at this price, but the internet drops in the evening.', videoIds: [] },
  },
], { offset: 2 });
